name: Deploy Website

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploying_to_surge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install Surge
        run: npm install --global surge
      - name: Deployment with Surge
        run: surge ./ ameenalam.surge.sh --token ${{ secrets.surge_token }}